### ISSUE TITLE
Change MySQL schema field type from BLOB to LONGBLOB 

### ISSUE THREAD

**Issue by danilvpetrov** [jmalloc/ax#159]
Some workflow states as well as the message can exceed standard MySQL BLOB size field (64 Kb). Please consider changing `data` field types from BLOB to LONGBLOB(4 Gb) in all relevant schemas.

**Comment by jmalloc** [comment]
Thanks man. 

By the way, I don't think there's any need to create a regular issue before submitting a PR for stuff that we've already discussed.

**Comment by danilvpetrov** [comment]
Ok, understood. Thanks for a quick merge.
