### ISSUE TITLE
Implement an inbound pipeline stage that acknowledges messages.

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/ax#18]
This pipeline stage would first forward to the next stage, then depending on whether that next stage returns an error perform one of the inbound message ops "ack", "retry" or "reject".

If no error is returned, the message is always ack'd; otherwise, the message should be retried or rejected based on some configurable retry policy.  The retry policy can be provided as a predicate function that accepts the `bus.InboundEnvelope` and returns a boolean - `true` to retry, `false` to reject.

**Comment by jmalloc** [comment]
There should also be some default retry policy that is used if no specific policy is provided. Perhaps retry if `m.DeliveryCount < 3`, otherwise reject.

**Comment by koden-km** [comment]
Added work in progress branch: 18-in-pipe-ack
