### ISSUE TITLE
Superficial message validation.

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/ax#23]
We need an inbound pipeline stage that performs superficial message validation. Superficial in this context means the kind of input validation that can be performed on a message-by-message basis without checking the state of the domain in any way.

This pipeline stage should immediately reject messages that can not be validated. However, there is currently no way for an input stage to return an error that *immediately* rejects a message. 

Two potential ways of implementing this spring to mind:

### 1. Error interface

Add an interface for errors that allow us to dictate whether they are likely to be transient or permanent, for example:

```go
type Error interface  {
    error 
    Temporary() bool
}
```

If `err.Temporary()` returns false, the `Acknowledger` stage would skip the retry policy and reject immediately. The validation error would need to implement this interface, and return `false` from `Temporary()`. This feels a little backwards because any error that doesn't implement this interface is assumed to be "temporary" however there is precedent for this kind of interface in [`net.Error`](https://golang.org/pkg/net/#Error).

I wouldn't advocate having the `Acknowledge` be aware of validation errors specifically. This is a fairly generic, extensible solution. That said, I feel like these kind of details can go unnoticed fairly easily, though I don't expect there to be very many places where this logic needs to be implemented. It certainly should not occur in application-defined handlers.

### 2. Allow multiple stages to call `InboundEnvelope.Done()`

In this approach, the validation stage would call `.Done(bus.OpReject)` on the inbound message envelope immediately. We'd need some way to signal to earlier stages (the `Acknowledger`) that `Done()` has already been called, and hence should not be called again. Perhaps `bus.InboundPipeline.Accept()` would change to accept a pointer-to-envelope and `.Done` could be set to `nil` once called. Otherwise; we could require that repeat calls to `Done()` are no-ops.

---

It's worth considering how these two approaches would interact with logging / tracing etc. For example, the first approach would allow us to build the pipeline like so:

```
acknowledger -> logging stage -> validator -> ...
```

Such that logging "just works" in the face of validation errors. For this reason alone I'm probably leaning towards that approach.

@koden-km @danilvpetrov I'm aware you guys haven't had much to do with this stuff yet, but I'd appreciate any thoughts / alternative solutions, etc :)

**Comment by jmalloc** [comment]
I forgot the most important part, which is to add a `ValidatedMessage` interface (or better name):

```
type ValidatedMessage interface {
    ax.Message
    Validate() error
}
```

The initial implementation of the validation pipeline stage would simply call this method on those messages that implement it.

I would also consider adding `Validate()` directly to `ax.Message`, but we do need to consider that in an event sourcing scenario, events that have already occurred may become "invalid" according to later software versions, so we'd need to be sure `Validate()` is only used when adding a new message into the system.

**Comment by jmalloc** [comment]
Thinking about this more, it makes far more sense to include this validation in the *outbound* pipeline instead / as well.

**Comment by jmalloc** [comment]
As discussed, it's probably better to use a specific struct type as a wrapper for errors that can not be retried.

The `receiver` can then unwrap the actual error before calling `ack.Reject(...)`

**Comment by danilvpetrov** [comment]
> We need an inbound pipeline stage that performs superficial message validation. Superficial in this context means the kind of input validation that can be performed on a message-by-message basis without checking the state of the domain in any way.

Want to make sure that I am on the same page in respect to the validation itself and its criteria. To me, the obvious validation failure would be to reject the message if message ID is not valid (if it's ever possible on the library level).  Are there any other criteria that we can already check at the validation stage?

**Comment by jmalloc** [comment]
> the obvious validation failure would be to reject the message if message ID is not valid

TBH I hadn't even considered validating the `Envelope` at this point, I was thinking only of application-defined validation of the `Message` itself. That said, I think it makes sense to validate the envelope too.

It's currently "impossible" for the IDs to be empty - they're UUIDs generated on the way out, and validated by the transport when unmarshaling the message - but that may not always be true as other transport implementations come along. The `MessageID` type already has a `Validate()` method too, but its error would need to be supplemented with some more contextual information so we know which field was invalid.

**Comment by jmalloc** [comment]
As per our discussion today, we need to allow the `ax.Sender` implementations to perform validation, rather than (or in addition to) the pipelines. So, in addition to everything we've already discussed, this issue will involve:

- Adding a `Validators []Validators` to `endpoint.SinkSender` and using them before passing the message to the sink
- Adding a `Validators []Validators` field to `Endpoint`, and using it to populate the senders wherever they are created (`endpoint.Endpoint` and `routing.Dispatcher`, iirc)

Also, let's keep `ValidationError`, but leave the idea of a "non retryable error" for a separate issue.
