### ISSUE TITLE
Add convenience functions for parsing/generating various IDs.

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/ax#45]
- `ax.MessageID`
- `saga.InstanceID`

Both of these types are implemented by `ident.ID`, which has the following methods for populating an ID:

- `Parse(s string) error`
- `MustParse(s string)`
- `GenerateUUID()`

It would be useful to have functions for each of these operations that return a new ID, for example:

```go
func GenerateMessageID() MessageID {
    var id MessageID
    id.GenerateUUID()
    return id
}
```

**Comment by koden-km** [comment]
So we want those 3 `ident.ID` functions for `MessageID` and `InstanceID`?

**Comment by jmalloc** [comment]
Yep
