### ISSUE TITLE
Implement a BBolt based DataStore.

### ISSUE THREAD

**Issue by jmalloc** [jmalloc/ax#5]
See https://github.com/coreos/bbolt, a fork of BoltDB that is actively maintained.

I was going to suggest an in-memory data store for testing, but a Bolt-backed store would be just as simple to use for testing and would also be a usable implementation for single-node endpoints.

The package would be `axbolt` and would need to implement:

- `persistence.DataStore`
- `persistence.Tx`
- `outbox.Repository`
- `saga.Repository`

**Comment by danilvpetrov** [comment]
Just a thought for this issue, since data serialising/unserialising for Bolt storage is happening only within `ax`, could we possibly use [`encoding/gob`](https://golang.org/pkg/encoding/gob/)? Its only Go-specific serialising/unserialising, right?

**Comment by jmalloc** [comment]
Hmm, I'm not really sure. My main question is how would we handle "schema upgrades" if the in-memory representation needed to change. Can we, with `gob`, add, remove and rename fields, etc?  Ideally we wouldn't have to run any kind of upgrade process over the stored data in such a scenario. These are the strengths of protocol buffers that led me to choose it for other long-term storage concerns.
